### DataFrame = A tabular data structure with rows and columns

In [19]:
import pandas as pd

In [20]:
data = {"Name":["Spongebob","Patrick","Squidward"],
        "Age":[30,35,50]
        }

df = pd.DataFrame(data)  # constructor
print(df)
df

        Name  Age
0  Spongebob   30
1    Patrick   35
2  Squidward   50

        Name  Age
0  Spongebob   30
1    Patrick   35
2  Squidward   50

In [21]:
df=pd.DataFrame(data,index=['a','b','c'])
df

        Name  Age
a  Spongebob   30
b    Patrick   35
c  Squidward   50

In [22]:
print(df.loc['a'])
df.loc['b']

Name    Spongebob
Age            30
Name: a, dtype: object

Name    Patrick
Age          35
Name: b, dtype: object

In [23]:
df.iloc[0]

Name    Spongebob
Age            30
Name: a, dtype: object

#### Add a new Column

In [24]:
df["Job"] = ["Cook","N/A","Cashier"]
df

        Name  Age      Job
a  Spongebob   30     Cook
b    Patrick   35      N/A
c  Squidward   50  Cashier

#### Add a new Row

In [25]:
new_row = pd.DataFrame([{"Name":"Sandy","Age":28,"Job":"Scientist"}],index=['d'])

# concatenate it with existing dataframe
df=pd.concat([df,new_row])
df

        Name  Age        Job
a  Spongebob   30       Cook
b    Patrick   35        N/A
c  Squidward   50    Cashier
d      Sandy   28  Scientist

#### Add new Rows

In [26]:
new_rows = pd.DataFrame([{"Name":"Crabs","Age":60,"Job":"Manager"},
                        {"Name":"Snoopy","Age":15,"Job":"Writer"}], index=['e','f']
                        )

df=pd.concat([df,new_rows])
df

        Name  Age        Job
a  Spongebob   30       Cook
b    Patrick   35        N/A
c  Squidward   50    Cashier
d      Sandy   28  Scientist
e      Crabs   60    Manager
f     Snoopy   15     Writer